project_id = "dcsisneuhgpuimonzpvu"

[functions.send-push-notification]
verify_jwt = false

[functions.cleanup-expired-verifications]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-image]
verify_jwt = false
